#!/usr/bin/env bash
# scripts/deploy_staging.sh — Round 4 Faille 4 finalisé
#
# Synthèse des 6 modèles round 4 :
#   - Worktree Git séparé (Gemini, Kimi, DeepSeek, ChatGPT)
#   - Docker staging avec ports décalés +10000 (DeepSeek, Kimi)
#   - Volumes prod montés en :ro (DeepSeek, ChatGPT, Gemini)
#   - Limites CPU/RAM hard pour ne pas pénaliser la prod (Qwen)
#   - Tag Git polybuild/run-{id}-pre AVANT toute modif (6/6)
#   - Phase 8 smoke obligatoire avant promote (6/6)
#   - Cleanup en bloc finally: (Gemini, complété par Phase 9)
#
# Usage:
#   ./deploy_staging.sh <run_id> <server_name> [<server_image>]
# Example:
#   ./deploy_staging.sh 2026-05-03_140000_a4f7 sstinfo sstinfo:latest

set -euo pipefail

RUN_ID="${1:?usage: deploy_staging.sh <run_id> <server_name> [<image>]}"
SERVER="${2:?missing server name}"
IMAGE="${3:-${SERVER}:latest}"

REPO_ROOT="$(git rev-parse --show-toplevel)"
WORKTREE_DIR="${REPO_ROOT}/.worktrees/staging-${RUN_ID}"
STAGING_BRANCH="polybuild/run-${RUN_ID}"
PRE_TAG="polybuild/run-${RUN_ID}-pre"
CONTAINER_NAME="polybuild-stg-${SERVER}-${RUN_ID//[^a-zA-Z0-9]/_}"

# Lecture du port prod (convention : .prod_port dans le dossier du serveur)
PROD_PORT_FILE="${REPO_ROOT}/services/${SERVER}/.prod_port"
if [[ -f "${PROD_PORT_FILE}" ]]; then
    PROD_PORT="$(cat "${PROD_PORT_FILE}")"
else
    PROD_PORT="8716"  # default SSTinfo
fi
STAGING_PORT="$(( PROD_PORT + 10000 ))"

echo "━━━ POLYBUILD deploy_staging ━━━"
echo "  run_id       : ${RUN_ID}"
echo "  server       : ${SERVER} (image=${IMAGE})"
echo "  branch       : ${STAGING_BRANCH}"
echo "  pre_tag      : ${PRE_TAG}"
echo "  staging_port : ${STAGING_PORT} (prod was ${PROD_PORT})"
echo "  worktree     : ${WORKTREE_DIR}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

cleanup() {
    local rc=$?
    echo "[cleanup] rc=$rc — removing staging artefacts"
    # Round 10 fix [.dockerignore éphémère]: ensure the transient .dockerignore
    # is restored even on error/SIGTERM during the build/run phases.
    if declare -F restore_dockerignore >/dev/null; then
        restore_dockerignore || true
    fi
    docker rm -f "${CONTAINER_NAME}" 2>/dev/null || true
    if [[ -d "${WORKTREE_DIR}" ]]; then
        git -C "${REPO_ROOT}" worktree remove -f "${WORKTREE_DIR}" 2>/dev/null || rm -rf "${WORKTREE_DIR}"
        git -C "${REPO_ROOT}" worktree prune || true
    fi
    exit $rc
}
trap cleanup EXIT INT TERM

# ── 1. Pre-tag for rollback (6/6 convergence) ────────────────────────
echo "[1/5] Tagging current HEAD as rollback point..."
git -C "${REPO_ROOT}" tag -f "${PRE_TAG}" HEAD
echo "      → ${PRE_TAG}"

# ── 2. Worktree isolated ─────────────────────────────────────────────
echo "[2/5] Creating worktree..."
git -C "${REPO_ROOT}" worktree add -B "${STAGING_BRANCH}" "${WORKTREE_DIR}" HEAD

# ── 3. Docker staging with RO prod volumes + resource caps ───────────
echo "[3/5] Building staging image from worktree..."
PROD_DATA_DIR="${REPO_ROOT}/services/${SERVER}/data"
if [[ ! -d "${PROD_DATA_DIR}" ]]; then
    echo "      WARN: ${PROD_DATA_DIR} not found, container will start without data volume"
    PROD_DATA_MOUNT=""
else
    PROD_DATA_MOUNT="-v ${PROD_DATA_DIR}:/app/data:ro"
fi

# Round 5 fix [K] (Audits 3+4 P0): build image FROM the worktree, not the
# pre-existing prod image. Otherwise the staging tested code is the prod code,
# not the candidate. Phase 8 smoke would validate nothing.
STAGING_IMAGE="${SERVER}:polybuild-${RUN_ID}"
if [[ ! -f "${WORKTREE_DIR}/Dockerfile" ]]; then
    echo "      ERROR: ${WORKTREE_DIR}/Dockerfile missing — cannot prove staging runs candidate code."
    echo "             Add a Dockerfile to your service repo or pass an explicit image."
    exit 1
fi

# Round 10 fix [.dockerignore éphémère] (Grok + ChatGPT + Kimi round 9 P1):
# without an isolated .dockerignore the build context drags data/, .polybuild/,
# runs/ and *.log into the image — bloated images, prod data leaking into
# staging container layers, slow builds. We materialise a transient ignore
# file scoped to the worktree, then restore the original (if any) on exit.
DOCKERIGNORE_PATH="${WORKTREE_DIR}/.dockerignore"
DOCKERIGNORE_BACKUP=""
if [[ -f "${DOCKERIGNORE_PATH}" ]]; then
    DOCKERIGNORE_BACKUP="${DOCKERIGNORE_PATH}.polybuild_bak"
    cp "${DOCKERIGNORE_PATH}" "${DOCKERIGNORE_BACKUP}"
fi
cat > "${DOCKERIGNORE_PATH}" <<'EOF'
# Auto-generated by polybuild deploy_staging.sh — restored on exit
data/
.polybuild/
runs/
*.log
.git/
.worktrees/
**/__pycache__
**/*.pyc
.venv/
node_modules/
EOF

restore_dockerignore() {
    if [[ -n "${DOCKERIGNORE_BACKUP}" ]] && [[ -f "${DOCKERIGNORE_BACKUP}" ]]; then
        mv "${DOCKERIGNORE_BACKUP}" "${DOCKERIGNORE_PATH}"
    elif [[ -f "${DOCKERIGNORE_PATH}" ]]; then
        rm -f "${DOCKERIGNORE_PATH}"
    fi
}

docker build -t "${STAGING_IMAGE}" "${WORKTREE_DIR}"
restore_dockerignore

echo "[3.5/5] Starting staging container..."
# shellcheck disable=SC2086
# Round 5 fix [L] (Audit 4 P0): bind to 127.0.0.1 only, not 0.0.0.0.
# Health-data staging must NOT be exposed on the LAN, even temporarily.
docker run -d \
    --name "${CONTAINER_NAME}" \
    --cpus="1" \
    --memory="1g" \
    -p "127.0.0.1:${STAGING_PORT}:${PROD_PORT}" \
    ${PROD_DATA_MOUNT} \
    -e POLYBUILD_STAGING=1 \
    -e SQLITE_READONLY=1 \
    -e QDRANT_READONLY=1 \
    -e MCP_PORT="${PROD_PORT}" \
    "${STAGING_IMAGE}"

# ── 4. Wait for healthy ──────────────────────────────────────────────
echo "[4/5] Waiting for staging to become healthy..."
HEALTHY=0
for i in $(seq 1 20); do
    # Round 5 fix (Audit 5 P2): --max-time prevents indefinite hang
    if curl -sf --max-time 3 "http://127.0.0.1:${STAGING_PORT}/health" >/dev/null 2>&1; then
        HEALTHY=1
        break
    fi
    sleep 1
done
if [[ "${HEALTHY}" -eq 0 ]]; then
    echo "      ERROR: staging not healthy after 20s"
    docker logs --tail 30 "${CONTAINER_NAME}" || true
    exit 1
fi
echo "      → staging healthy at http://127.0.0.1:${STAGING_PORT}"

# ── 5. Phase 8 smoke ─────────────────────────────────────────────────
echo "[5/5] Running Phase 8 production smoke..."
# Round 6 [T2]: pass --rollback-force-clean because we're operating on the
# DEDICATED staging worktree (not the user's main repo). The flag is safe here.
if ! uv run python -m polybuild.phases.phase_8_prod_smoke \
    --endpoint "http://127.0.0.1:${STAGING_PORT}/jsonrpc" \
    --golden "${REPO_ROOT}/tests/golden/${SERVER}_smoke.json" \
    --rollback-tag "${PRE_TAG}" \
    --rollback-force-clean \
    --repo-dir "${WORKTREE_DIR}" \
    --window-s 300; then
    echo "      ✘ Phase 8 smoke FAILED — rollback already triggered"
    exit 1
fi

echo "✔ Staging validated. Promote with:"
echo "    git checkout main && git merge --ff-only ${STAGING_BRANCH} && git tag polybuild/run-${RUN_ID}-ok"
exit 0
